### ISSUE TITLE
An error in the `open` command

### ISSUE THREAD

**Issue by WoosukKwon** [jaywonchung/reason#3]
Thanks for the nice project!
I found this error message when I tried the `open` command on my MacBook:
`Invalid editor command: 'Os { code: 2, kind: NotFound, message: "No such file or directory" }`
Please check out this problem.
Let me know if you need more information about my environment.

**Comment by jaywonchung** [comment]
Hi, Woosuk! Thanks for trying out and reporting :)

Can you check your viewer command in the config? Can you open your PDF viewer in the commandline with that viewer command?

The example MacOS config in the examples directory might also help.

**Comment by jaywonchung** [comment]
Hmm, reading your question again, I'm not sure why reason complains about the editor command when you used the open command. I'll look into this. Could you provide your configuration?

**Comment by WoosukKwon** [comment]
Thanks for the quick response, Jaewon.
I didn't touch the config file of reason, so it will be exactly the same as the default one.

**Comment by jaywonchung** [comment]
Oh, then you might not have zathura (which is the default viewer). It's a PDF viewer that supports vim navigtion key bindings. See https://github.com/zegervdv/homebrew-zathura if you want to try it out.

If not, you should set your own PDF viewer in the config. The example MacOS config in the examples directory will definitely help.

**Comment by WoosukKwon** [comment]
Oh I see. Thanks!

**Comment by jaywonchung** [comment]
Feel free to re-open when the problem persists!
